### ISSUE TITLE
Can't get league to load

### ISSUE THREAD

**Issue by feelitallaround** [MethSarcus/MyFantasyNumbers#29]
**Describe the bug**
The site won't load my league from Sleeper. It gets stuck loading roster and settings.

**To Reproduce**
Put in league ID, pick sleeper, pick 2019, attempt to proceed. 

**League ID**
474039681051258880

**Additional context**
Attempted using brave browser, Google Chrome, Mozilla Firefox, internet explorer, same problem with each

**Comment by MethSarcus** [comment]
Working on this currently, it looks like the problem is your league was not filled and my site is crashing when given empty teams with no owners, gonna see what I can get solved with this now

**Comment by feelitallaround** [comment]
Thanks Seth! The league actually has been filled the whole time. Maybe it's
because people don't have draft spots assigned yet. I'm glad to assign
random ones if it will get it worked out. Naturally, I was waiting to see
the 2019 season long potential points on MFN before setting it, since the
tallying stops at the end of the regular season on sleeper. Catch 22 to the
max. Let me know how I can help!

Matt

**Comment by feelitallaround** [comment]
I actually seem to have given you the wrong league ID. I might be a moron. The one following is the league I meant to inquire about:
428654799899070464 
I'm going to try it again real quick. Yikes.

**Comment by feelitallaround** [comment]
It 100% works on the other league that I was trying to get to work. I'm a grade A buffoon. Thanks again, and sorry for wasting your time.

**Comment by MethSarcus** [comment]
No problem, it actually did inform me on a lot of potential bugs/errors that can occur so this was a very useful issue to spend some time on, happy to hear it works and thanks for keeping me updated!
