### ISSUE TITLE
Can't load 2020 League Page

### ISSUE THREAD

**Issue by cire52** [MethSarcus/MyFantasyNumbers#38]
After inputting my 2020 Sleeper league ID, the site infinitely loads "Getting Player Stats"

**To Reproduce**
Input League ID
Select Sleeper as platform
Select 2020 season
Click Submit

**League ID**
515619592750796800

**Expected behavior**
I expect to be able to view my league's page.
Thank you!

**Comment by MethSarcus** [comment]
Unfortunately after trying a few different ways of gathering the data needed to get the site to run without sleeper providing the point totals of rostered players directly I am going to have to write some sort of data scraping chrome extension that will need to be downloaded to get the site to run, working on implementing that right now

**Comment by MethSarcus** [comment]
Fixed
