### ISSUE TITLE
https://sethmarcus.tech/MyFantasyNumbers/ sits on "getting player stats"

### ISSUE THREAD

**Issue by SolSolis69** [MethSarcus/MyFantasyNumbers#39]
Hi there,

Trying to use your webpage but I'm not able to get in to use it any longer.  We used this last season to calculate our potential points in the playoffs.

Once I enter in our league ID and choose 2020 as the year, it gets to "Getting Player Stats" and never advances again.  This was attempted in multiple browsers on desktop, as well as, on mobile. 

Our league ID is 517428769480511488 and is on Sleeper.  Please let me know if you need anything else.  Really hoping to get this up and running again.  It was so clutch last year.

Thanks!
Derek Harris

**Comment by MethSarcus** [comment]
Make sure to do a hard refresh of the page but it should work now, thanks for checking it out and opening this issue and sorry for the fresh wave of bugs some of the pages have
