### ISSUE TITLE
Stuck at "Getting Weekly Stats" status

### ISSUE THREAD

**Issue by shanegiroux** [MethSarcus/MyFantasyNumbers#69]
**Describe the bug**
Stuck at "Getting weekly stats"

**To Reproduce**
1. Go to ['Homepage'](https://methsarcus.github.io/MyFantasyNumbers/)
2. Enter Sleeper league id
3. Click Submit
4. Tool starts loading/progress of "Getting weekly stats" and does not finish

**League ID**
848286961255976960

**Expected behavior**
Would see the numbers :)

**Screenshots**

**Additional context**
It appears stat asset files beyond Week 1 are giving a 404. There is a Build fail happening in the Actions that is likely preventing new stats from properly being deployed?

**Comment by MethSarcus** [comment]
@shanegiroux The homepage you linked to is github hosted not where the site is actually located,I tested your leagueID at https://www.myfantasynumbers.com/ and it worked can you see if that fixes it?

**Comment by shanegiroux** [comment]
Ah, my apologies. I made an assumption and overlooked where the actual site was hosted. Found the repo, found the Actions, went to the URl in there. My bad! Indeed, it works at the proper domain.

**Comment by MethSarcus** [comment]
No problem and thanks for using the site! I wasn't aware that url was up ill make sure to take it down to avoid future confusion
