### ISSUE TITLE
Stats Pull Lokcs up

### ISSUE THREAD

**Issue by littleearsmusic** [MethSarcus/MyFantasyNumbers#73]
**Describe the bug**
Site locks up on "Getting Weekly Stats" after entering League ID

**To Reproduce**

**League ID**
861487821632966656

**Expected behavior**

**Screenshots**

**Additional context**
<img width="917" alt="Screen Shot 2023-01-06 at 11 34 04 AM" src="https://user-images.githubusercontent.com/57452684/211086163-fe76919e-0951-4abc-9079-eb652796c10a.png">

**Comment by MethSarcus** [comment]
Should be fixed
