### ISSUE TITLE
Sleeper BBALL

### ISSUE THREAD

**Issue by littleearsmusic** [MethSarcus/MyFantasyNumbers#76]
seth, 
love the work you've done on this - i attempted to drop in our sleeper basketball ID and it hung up on getting player stats. not sure if its possible to translate - but we are in Y3 of a dynasty sleeper basketball league and would love to capture the data as best we can. would love to be able to use the site for that. 

thanks so much,
m

**Comment by MethSarcus** [comment]
Thanks for using stoked you like it, unfortunately (currently) the site is football only, I might consider expanding in the future but atm basketball is not supported, also be sure to check out the new site location at www.visualeague.com
